%Load RCNN
lgraph = load('RCNN.mat').lgraph;

%Training options
options = trainingOptions('adam', ...
    'CheckpointPath', 'D:\Checkpoint', ...
    'ExecutionEnvironment', 'multi-gpu', ...
    'InitialLearnRate', 1e-3, ...
    'LearnRateSchedule', 'piecewise', ...
    'L2Regularization', 1e-4, ...
    'MaxEpochs', 80, ...
    'MiniBatchSize', 32, ...
    'Verbose', true, ...
    'VerboseFrequency', 50, ...
    'GradientDecayFactor', 0.9, ...
    'SquaredGradientDecayFactor', 0.999);

%Train
[trainedDetector, info] = trainFasterRCNNObjectDetector(trainingDataTbl, lgraph, ...
    options, 'NegativeOverlapRange',[0 0.3], ...
                      'PositiveOverlapRange',[0.5 1]);                
                  



